### testExame_Paciente.rest

### Necessário para pegar o token    
### Post  
# @name loginAutenticado  
POST http://localhost:40000/Login HTTP/1.1  
content-type: application/json  

{      
  "username": "qwe",  
  "password": "qwe"  
}  

### Seta o token  
@accessToken = {{loginAutenticado.response.body.$.token}}  
@username = {{loginAutenticado.response.body.$.username}}  

### teste de buscar todos os registros de exame_paciente  
GET http://localhost:40000/GetAllExamePaciente HTTP/1.1  
content-type: application/json  
Authorization: Bearer {{accessToken}}  

### teste de buscar exame_paciente por ID  
POST http://localhost:40000/GetExamePacienteByID HTTP/1.1  
content-type: application/json  
Authorization: Bearer {{accessToken}}  

{     
  "exame_paciente_id": 1  
}  

### teste de inserção em exame_paciente  
POST http://localhost:40000/InsertExamePaciente HTTP/1.1  
content-type: application/json  
Authorization: Bearer {{accessToken}}  

{      
  "paciente_id": 1,  
  "exame_id": 1,  
  "data_exame": "2025-11-05",  
  "laudo": "Laudo inicial: dentro da normalidade."  
}  

### teste de atualização de exame_paciente  
POST http://localhost:40000/UpdateExamePaciente HTTP/1.1  
content-type: application/json  
Authorization: Bearer {{accessToken}}  

{      
  "exame_paciente_id": 1,  
  "paciente_id": 1,  
  "exame_id": 1,  
  "data_exame": "2025-11-06",  
  "laudo": "Laudo revisado: observação complementar."  
}  

### teste de deleção (soft delete) em exame_paciente  
POST http://localhost:40000/DeleteExamePaciente HTTP/1.1  
content-type: application/json  
Authorization: Bearer {{accessToken}}  

{      
  "exame_paciente_id": 1  
}
