### testPacientes.rest

### Necessário para pegar o token
### Post
# @name loginAutenticado
POST http://localhost:40000/Login HTTP/1.1
content-type: application/json

{
  "UserName": "qwe",
  "Password": "qwe"
}

### Seta o token
@accessToken = {{loginAutenticado.response.body.$.token}}
@username = {{loginAutenticado.response.body.$.username}}


### teste de buscar todos os pacientes
GET http://localhost:40000/GetAllPacientes HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

### teste de buscar paciente por ID
POST http://localhost:40000/GetPacienteByID HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "pacienteid": 1
}

### teste de inserção de paciente
POST http://localhost:40000/InsertPacientes HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "cpf": "12345678901",
  "nome": "João da Silva",
  "endereco": "Rua Teste, 123",
  "telefone": "+55 11 90000-0000"
}

### teste de atualização de paciente
POST http://localhost:40000/UpdatePacientes HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "pacienteid": 1,
  "cpf": "12345678901",
  "nome": "João da Silva (Atualizado)",
  "endereco": "Av. Central, 200",
  "telefone": "+55 11 98888-7777"
}

### teste de deleção (soft delete) de paciente
POST http://localhost:40000/DeletePacientes HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "pacienteid": 1
}
